server:
  port: 2004
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai #GMT+8
  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/LostAndFound?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #rabbitMQ
  rabbitmq:
    host: *
    port: 5672
    username: guest
    password: guest
    virtual-host:
  #配置redis
  redis:
    host:

